server:
  port: 8080
spring.application.name: PizzaMaker
server.context-path: /
spring.datasource.url: mongodb://userpizza:1234@localhost:27017/auchan-init-stack
spring.datasource.driver-class-name: com.mongodb.MongoDriverInformation
spring.data.mongodb.authentication-database: admin
spring.data.mongodb.username: userpizza
spring.data.mongodb.password: 1234
spring.data.mongodb.database: auchan-init-stack
spring.data.mongodb.port: 27017
spring.data.mongodb.host: localhost

